name: Refresh HelloAsso Tokens
on:
  schedule:
    - cron: '0 0 */25 * *' # Tous les 25 jours
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git and SSH
        run: |
          git config user.name "ObjethequeBretagne"
          git config user.email "cornouailleobjethequedev@gmail.com"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Get New Tokens
        id: get-tokens
        run: |
          response=$(curl -X POST https://api.helloasso.com/oauth2/token \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=client_credentials" \
          -d "client_id=${{ secrets.HELLOASSO_CLIENT_ID }}" \
          -d "client_secret=${{ secrets.HELLOASSO_CLIENT_SECRET }}")
          
          echo $response | jq -r .access_token > access_token.txt
          echo $response | jq -r .refresh_token > refresh_token.txt

      - name: Update Access Token
        run: |
          ACCESS_TOKEN=$(cat access_token.txt)
          echo "$ACCESS_TOKEN" | gh secret set HELLOASSO_ACCESS_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Refresh Token
        run: |
          REFRESH_TOKEN=$(cat refresh_token.txt)
          echo "$REFRESH_TOKEN" | gh secret set HELLOASSO_REFRESH_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: always()
        run: |
          rm -f access_token.txt refresh_token.txt
