name: Update Events JSON

on:
  schedule:
    - cron: '0 0 * * 1' # Tous les lundis à minuit
  workflow_dispatch: # Déclenchement manuel

jobs:
  update-events:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Version LTS de Node.js

      - name: Install dependencies
        run: npm install

      - name: Fetch events from HelloAsso
        run: node fetch-events.js
        env:
          HELLOASSO_ACCESS_TOKEN: ${{ secrets.HELLOASSO_ACCESS_TOKEN }}
          HELLOASSO_REFRESH_TOKEN: ${{ secrets.HELLOASSO_REFRESH_TOKEN }}
          HELLOASSO_CLIENT_ID: ${{ secrets.HELLOASSO_CLIENT_ID }}
          HELLOASSO_CLIENT_SECRET: ${{ secrets.HELLOASSO_CLIENT_SECRET }}

      - name: Commit and push changes
        run: |
          git config user.name "ObjethequeBretagne"
          git config user.email "cornouailleobjethequedev@gmail.com"
          git add public/events.json
          if git diff --cached --quiet; then
            echo "Aucun changement détecté, aucune action requise."
          else
            git commit -m "Mise à jour des événements depuis HelloAsso"
            git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ObjethequeBretagne/site.git astro-version
          fi

